apiVersion: v1
kind: ConfigMap
metadata:
  name: approostio-config
  namespace: {{ .Release.Namespace }}
data:
  REACT_APP_API_HOST:  {{ .Values.enterprise.domain_url }}/api
  REACT_APP_REDIRECT_URI: {{ .Values.enterprise.domain_url }}/login
  REACT_APP_ENTERPRISE_LOGO: {{ .Values.enterprise.logo }}
  REACT_APP_REMOTE_CONSOLE_PROXY: {{ .Values.enterprise.consoleProxy }}
  REACT_APP_GOOGLE_CLIENT_ID: {{ .Values.auth.googleClientID }}
  REACT_APP_AZURE_CLIENT_ID: {{ .Values.auth.azureClientID }}
  REACT_APP_GITHUB_CLIENT_ID: {{ .Values.auth.githubClientID }}
  REACT_APP_LINKEDIN_CLIENT_ID: {{ .Values.auth.linkedinClientID }}
  REACT_APP_OKTA_CLIENT_ISSUER:  {{ .Values.auth.oktaClientIssuer }}
  REACT_APP_OKTA_CLIENT_ID: {{ .Values.auth.oktaClientID }}
  REACT_APP_AZURE_ADFS_CLIENT_ISSUER: {{ .Values.auth.azureADFSClientIssuer }}
  REACT_APP_AZURE_ADFS_CLIENT_ID: {{ .Values.auth.azureADFSClientID }}
  REACT_APP_COOKIE_SECURE: "{{ .Values.enterprise.cookieSecure }}"
  REACT_APP_COOKIE_DOMAIN: {{ .Values.enterprise.cookieDomain }}
  REACT_APP_ROOST_VER: {{ .Values.enterprise.roostVersion }}
  REACT_APP_DB_VER: {{ .Values.enterprise.roostVersion }}
  REACT_APP_EMAIL_SENDER:  {{ .Values.enterprise.email.sender }}
  REACT_APP_EMAIL_SENDER_PASS: {{ .Values.enterprise.email.senderPass }} 
  REACT_APP_IS_DEPLOYED_IN_ECS: "true"
  REACT_APP_ONLY_ROOSTGPT: "{{ .Values.roostgpt.onlyGPT }}"
  REACT_APP_NO_AUTH: "{{ .Values.auth.noAuth }}"
--- 

apiVersion: v1
kind: Service
metadata:
  name: roostai-react-app
  namespace: {{ .Release.Namespace }}
spec:
  # type: NodePort
  selector:
    app: roostai-react-app
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      # nodePort: 30424  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roostai-react-app
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roostai-react-app
  template:
    metadata:
      labels:
        app: roostai-react-app
    spec:
     # hostNetwork: true
      containers:
      - name: roostai-react-app
        image: zbio/roost-web:{{ .Values.enterprise.roostVersion }}
        envFrom:
          - configMapRef:
              name: approostio-config
        ports:
          - containerPort: 4200
        imagePullPolicy: Always
---