apiVersion: v1
kind: Service
metadata:
  name: roost-backend-server
  namespace: {{ .Release.Namespace }}
spec:
  # type: NodePort
  selector:
    app: backend-service
  ports:
    - protocol: TCP
      port: 60003
      targetPort: 60003
      name: roost-eaas
      # nodePort: 30003  
    - protocol: TCP
      port: 60007
      targetPort: 60007
      name: roost-gpt
---

