{{- if .Values.eaas.enabled }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: release-config
  namespace: {{ .Release.Namespace }}
data:
  VERBOSE_LEVEL: "{{ .Values.verboseLevel }}"
  ENT_SERVER: {{ .Values.enterprise.domain_url }}
  AUTH_KEY: {{ .Values.auth.localAuthKey }}
  ROOST_VER: {{ .Values.enterprise.roostVersion }}
  DEPLOYED_IN_K8S: "true"
  ROOST_AI_NS: {{ .Release.Namespace }}
--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roostai-eaas-app-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
{{- if .Values.efs.enabled }}
  storageClassName: efs-sc
{{- end }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: roostai-eaas-app
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
    #  hostNetwork: true
      containers: 
        - name: roostai-eaas-app
          image: zbio/roost-eaas:{{ .Values.enterprise.roostVersion }}
          envFrom:
            - configMapRef:
                name: release-config
          volumeMounts:
            - mountPath: /var/tmp/Roost
              name: roostai-eaas-app-data
          ports:
            - containerPort: 60003
          imagePullPolicy: Always
      volumes:
        - name: roostai-eaas-app-data
          persistentVolumeClaim:
            claimName: roostai-eaas-app-data
---
{{- end }}