{{- $hasTls := or .Values.gateway.tls.enabled (and .Values.acm.enabled (ne .Values.acm.arn "")) -}}
{{- $useHttp := and (eq .Values.cloudConfig.clusterType "local") (not $hasTls) -}}
{{- $protocol := ternary "http" "https" $useHttp -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: roost-app-config
  namespace: {{ .Release.Namespace }}
data:
  NODE_ENV: 'production'
  DEFAULT_PORT: '3000'
  API_HOST_URL: '{{ $protocol }}://{{ .Values.enterprise.domainURL }}/api'
  LOGIN_REDIRECT_URL: '{{ $protocol }}://{{ .Values.enterprise.domainURL }}/login'
  NODE_DOMAIN_OR_IP: '{{ .Values.enterprise.domainURL }}'

  ROOST_VER: '{{ .Values.roostConfig.roostVersion }}'
  DB_VER: '{{ .Values.roostConfig.dbVersion }}'

  # Auth Config
  GOOGLE_CLIENT_ID: '{{ .Values.auth.googleClientID }}'
  GOOGLE_CLIENT_SECRET: '{{ .Values.auth.googleClientSecret }}'
  AZURE_CLIENT_ID: '{{ .Values.auth.azureClientID }}'
  AZURE_CLIENT_SECRET: '{{ .Values.auth.azureClientSecret }}'
  AZURE_TENANT_ID: '{{ .Values.auth.azureTenantID }}'
  GITHUB_CLIENT_ID: '{{ .Values.auth.githubClientID }}'
  GITHUB_CLIENT_SECRET: '{{ .Values.auth.githubClientSecret }}'
  LINKEDIN_CLIENT_ID: '{{ .Values.auth.linkedinClientID }}'
  LINKEDIN_CLIENT_SECRET: '{{ .Values.auth.linkedinClientSecret }}'
  OKTA_CLIENT_ISSUER: '{{ .Values.auth.oktaClientIssuer }}'
  OKTA_CLIENT_ID: '{{ .Values.auth.oktaClientID }}'
  OKTA_CLIENT_SECRET: '{{ .Values.auth.oktaClientSecret }}'
  AZURE_ADFS_CLIENT_ISSUER: '{{ .Values.auth.azureADFSClientIssuer }}'
  AZURE_ADFS_CLIENT_ID: '{{ .Values.auth.azureADFSClientID }}'
  AZURE_ADFS_CLIENT_SECRET: '{{ .Values.auth.azureADFSClientSecret }}'
  AUTH0_CLIENT_ISSUER: '{{ .Values.auth.auth0ClientIssuer }}'
  AUTH0_CLIENT_ID: '{{ .Values.auth.auth0ClientID }}'
  AUTH0_CLIENT_SECRET: '{{ .Values.auth.auth0ClientSecret }}'
  PING_FEDERATE_CLIENT_ISSUER: '{{ .Values.auth.pingFederateClientIssuer }}'
  PING_FEDERATE_CLIENT_ID: '{{ .Values.auth.pingFederateClientID }}'
  PING_FEDERATE_CLIENT_SECRET: '{{ .Values.auth.pingFederateClientSecret }}'

  # Client Config
  ORG_NAME: '{{ .Values.enterprise.orgName }}'
  ORG_ADMIN_EMAIL: '{{ .Values.enterprise.orgAdminEmail }}'
  ORG_EMAIL_DOMAIN: '{{ .Values.enterprise.orgEmailDomain }}'
  ORG_APP_NAME: '{{ .Values.enterprise.appName }}'
  EAAS_SVC: '{{ .Values.eaasServerIp }}'
  EAAS_SERVER_USERNAME: '{{ .Values.eaasServerUsername }}'
  EAAS_SERVER_KEY_PATH: '{{ .Values.eaasServerPemKey }}'

  # DB Config
  DB_HOST_TYPE: '{{ .Values.database.type }}'
  {{- if .Values.database.integrated }}
    {{- if eq .Values.database.type "postgres" }}
  DB_HOST: 'roost-postgres-db-svc.{{ .Release.Namespace }}.svc.cluster.local'
  DB_PORT: '5432'
  DB_USERNAME: 'postgres'
  DB_PASSWORD: 'Roost#123'
  DB_SCHEMA_NAME: 'roostio'
  POSTGRES_PASSWORD: 'Roost#123'
  POSTGRES_USER: 'postgres'
  POSTGRES_DB: 'roostio'
    {{- else }}
  DB_HOST: 'roost-mysql-db-svc.{{ .Release.Namespace }}.svc.cluster.local'
  DB_PORT: '3306'
  DB_USERNAME: '{{ .Values.database.user }}'
  DB_PASSWORD: '{{ .Values.database.password }}'
  DB_SCHEMA_NAME: '{{ .Values.database.schema }}'
  MYSQL_ROOT_PASSWORD: '{{ .Values.database.rootPassword }}'
  MYSQL_DATABASE: '{{ .Values.database.schema }}'
    {{- end }}
  {{- else }}
  DB_HOST: '{{ .Values.database.host }}'
  DB_PORT: '{{ .Values.database.port }}'
  DB_USERNAME: '{{ .Values.database.user }}'
  DB_PASSWORD: '{{ .Values.database.password }}'
  DB_SCHEMA_NAME: '{{ .Values.database.schema }}'
  {{- end }}

  # Email Config
  EMAIL_SENDER: '{{ .Values.email.sender }}'
  EMAIL_SENDER_PASS: '{{ .Values.email.senderPass }}'
  EMAIL_SMTP: '{{ .Values.email.smtp }}'
  EMAIL_SMTP_PORT: '{{ .Values.email.smtpPort }}'

  # Other Config
  LICENSE_KEY: '{{ .Values.roostConfig.licenseKey }}'
  JWT_SECRET: '{{ .Values.auth.jwt_secret }}'
  USE_NO_AUTH: '{{ .Values.auth.noAuth }}'
  USE_AS_ROOST_CLOUD_SERVER: '{{ .Values.roostConfig.useAsRoostCloudServer }}'
  ECS_MODE: '{{ .Values.roostConfig.ecs_mode }}'

---
apiVersion: v1
kind: Service
metadata:
  name: roostai-nest-server # roost-app-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: roost-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roost-app-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
{{- include "cluster.storageClassName" . | indent 2 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roost-app
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.roostConfig.roostAppReplicas }}
  selector:
    matchLabels:
      app: roost-app
  template:
    metadata:
      labels:
        app: roost-app
      annotations:
        checksum/config: {{ toYaml (pick .Values "database" "enterprise" "email" "auth" "eaasServerIp" "eaasServerPemKey" "eaasServerUsername" "roostConfig") | sha256sum }}
    spec:
      containers:
        - name: roost-app
          image: zbio/roost-app:{{ .Values.roostConfig.roostVersion }}
          envFrom:
            - configMapRef:
                name: roost-app-config
          volumeMounts:
            - mountPath: /var/tmp/Roost
              name: roost-app-data
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      volumes:
        - name: roost-app-data
          persistentVolumeClaim:
            claimName: roost-app-pvc

---

