{{- if and (eq .Values.cloudConfig.clusterType "eks") .Values.installClusterResources.storageClass }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass }}
provisioner: efs.csi.aws.com
parameters:
  fileSystemId: {{ .Values.cloudConfig.efsFileSystemID }}
  provisioningMode: efs-ap
  basePath: /var/tmp/Roost
  directoryPerms: "770"
  gidRangeStart: "10001"
  gidRangeEnd: "10001"
  ensureUniqueDirectory: "true"
  subPathPattern: "/${.PVC.namespace}-${.PVC.name}" # aws supports only 4 level path. /var/tmp/Roost is already 3 level
reclaimPolicy: Retain
volumeBindingMode: Immediate

---
# EBS - used by MySQL
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.database.storage.storageClass }}
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---
{{- end }}

{{- if and (eq .Values.cloudConfig.clusterType "aks") .Values.installClusterResources.storageClass }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass }}
provisioner: file.csi.azure.com
parameters:
  protocol: nfs
  skuName: Premium_LRS # NFS protocol requires Premium tier; options: Premium_LRS, Premium_ZRS, Standard_LRS, Standard_GRS, Standard_ZRS, Standard_RAGRS, Standard_RAGZRS
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nconnect=4

---
{{- end}}

{{- if and (eq .Values.cloudConfig.clusterType "local") .Values.installClusterResources.storageClass }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storageClass }}
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  storageClassName: roost-sc-local
  hostPath:
    path: {{ .Values.cloudConfig.localStoragePath }}
---
{{- end}}
