apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: roost-pod-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ['']
    resources:
      - 'pods'
      - 'pods/log'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
      - 'create'
      - 'delete'
      - 'update'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roost-pod-role-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: roost-pod-role
  apiGroup: rbac.authorization.k8s.io

---

