{{- if and (.Values.database.integrated) (eq .Values.database.type "postgres") }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: roost-postgres-db-config
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_PASSWORD: "{{ .Values.database.password }}"
  POSTGRES_USER: "{{ .Values.database.user }}"
  POSTGRES_DB: "{{ .Values.database.schema }}"

---
apiVersion: v1
kind: Service
metadata:
  name: roost-postgres-db-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: roost-postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roost-postgres-db
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roost-postgres-db
  template:
    metadata:
      labels:
        app: roost-postgres-db
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
      containers:
        - name: roost-postgres-db
          image: postgres:15.2 # {{ .Values.roostConfig.dbVersion }}
          envFrom:
            - configMapRef:
                name: roost-postgres-db-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: roost-postgres-db-data
          ports:
            - containerPort: 5432
          imagePullPolicy: Always
      volumeClaimTemplates:
      - metadata:
          name: roost-postgres-db-data
          annotations:
            "helm.sh/resource-policy": keep
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.database.storage.size }}
          storageClassName: {{ .Values.database.storage.storageClass }}

---
{{- end }}
