apiVersion: v1
kind: Service
metadata:
  name: roost-backend-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    svc_group: roost-backend-svc
  ports:
    - name: roost-ai-server
      protocol: TCP
      port: 60007
      targetPort: ai-server-port
{{- if .Values.roostConfig.enableClusterLauncher }}
    - name: roost-launcher
      protocol: TCP
      port: 60002
      targetPort: launcher-port
{{- end }}
{{- if .Values.roostConfig.enableEaasServer }}
    - name: roost-eaas
      protocol: TCP
      port: 60003
      targetPort: eaas-port
{{- end }}

---

