apiVersion: v1
kind: Service
metadata:
  name: roost-backend-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    svc_group: roost-backend-svc
  ports:
    - name: roost-ai-server
      protocol: TCP
      port: 60007
      targetPort: ai-server-port

---

