# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

database:
  integrated: true # true/false
  type: mysql # mysql/postgres

  # Specify, if database.integrated = false
  host: ''
  port: 3306
  schema: ''
  user: ''
  password: ''

auth:
  noAuth: false # true/false

  googleClientID: ''
  googleClientSecret: ''

  azureClientID: ''
  azureClientSecret: ''

  githubClientID: ''
  githubClientSecret: ''

  linkedinClientID: ''
  linkedinClientSecret: ''

  oktaClientIssuer: ''
  oktaClientID: ''
  oktaClientSecret: ''

  azureADFSClientIssuer: ''
  azureADFSClientID: ''
  azureADFSClientSecret: ''

  # REQUIRED: local auth key for roost, example : 06b5e496f8f53139de7d2cc03b1e71ce
  localKey: ''

enterprise:
  # logo url
  logo: https://roost.ai/hubfs/logos/Roost.ai-logo-gold.svg
  # domain where roostAI will be hosted, example : test.example.com
  domainURL: ''
  # configure organisation name - don't use spaces
  orgName: ''
  # admin email, example suppor@zb.io
  orgAdminEmail: ''
  # email domain, example zb.io
  orgEmailDomain: ''

# configure email for email notification support
email:
  sender: ''
  senderPass: ''
  smtp: ''
  smtpPort: ''

roostConfig:
  licenseKey: '' # provide license key obtained from roost
  jwtSecret: '' # 32-character-secure-long-secret

  enableRoostGPT: true # true/false
  enableEaasServer: false # true/false
  enableClusterLauncher: false # true/false
  enableJumphost: false # true/false
  onlyGPT: false # true/false

  # roostVersion and dbVersion can be based on helm chart versioning
  roostVersion: 'latest'
  dbVersion: 'v1.1.0'

  verboseLevel: 4

cloudConfig:
  clusterType: '' # eks/gke/aks/local
  efsFileSystemID: '' # Specify only if cloud_provider.type = eks

# provide aws acm arn for certificates for eks
acm:
  enabled: false
  arn: ''

# google cloud cert manager
certificateManager:
  createNew: false
  existingCert: ''

# azure key vault cert identifier
azureCerts:
  enabled: false
  # certificate identifier
  # https://<vault-name>.vault.azure.net/certificates/<certificate-name>/<certificate-version>
  identifier: ''
